# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Attachment1")

model_instance <- Attachment1$new()

test_that("download", {
  # tests for the property `download` (str)

  # uncomment below to test the property
  #expect_equal(model.instance$`download`, "EXPECTED_RESULT")
})

test_that("href", {
  # tests for the property `href` (str)

  # uncomment below to test the property
  #expect_equal(model.instance$`href`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (str)

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("md5sum", {
  # tests for the property `md5sum` (str)

  # uncomment below to test the property
  #expect_equal(model.instance$`md5sum`, "EXPECTED_RESULT")
})

test_that("size", {
  # tests for the property `size` (int)

  # uncomment below to test the property
  #expect_equal(model.instance$`size`, "EXPECTED_RESULT")
})

test_that("width", {
  # tests for the property `width` (int)

  # uncomment below to test the property
  #expect_equal(model.instance$`width`, "EXPECTED_RESULT")
})

test_that("height", {
  # tests for the property `height` (int)

  # uncomment below to test the property
  #expect_equal(model.instance$`height`, "EXPECTED_RESULT")
})
