# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ImageFile")

model_instance <- ImageFile$new()

test_that("release_timestamp", {
  # tests for the property `release_timestamp` (str)
  # The date the object was released.

  # uncomment below to test the property
  #expect_equal(model.instance$`release_timestamp`, "EXPECTED_RESULT")
})

test_that("documents", {
  # tests for the property `documents` (List[str])
  # Documents that provide additional information (not data file).

  # uncomment below to test the property
  #expect_equal(model.instance$`documents`, "EXPECTED_RESULT")
})

test_that("lab", {
  # tests for the property `lab` (str)
  # Lab associated with the submission.

  # uncomment below to test the property
  #expect_equal(model.instance$`lab`, "EXPECTED_RESULT")
})

test_that("award", {
  # tests for the property `award` (str)
  # Grant associated with the submission.

  # uncomment below to test the property
  #expect_equal(model.instance$`award`, "EXPECTED_RESULT")
})

test_that("accession", {
  # tests for the property `accession` (str)
  # A unique identifier to be used to reference the object prefixed with IGVF.

  # uncomment below to test the property
  #expect_equal(model.instance$`accession`, "EXPECTED_RESULT")
})

test_that("alternate_accessions", {
  # tests for the property `alternate_accessions` (List[str])
  # Accessions previously assigned to objects that have been merged with this object.

  # uncomment below to test the property
  #expect_equal(model.instance$`alternate_accessions`, "EXPECTED_RESULT")
})

test_that("collections", {
  # tests for the property `collections` (List[str])
  # Some samples are part of particular data collections.

  # uncomment below to test the property
  #expect_equal(model.instance$`collections`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (str)
  # The status of the metadata object.

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("revoke_detail", {
  # tests for the property `revoke_detail` (str)
  # Explanation of why an object was transitioned to the revoked status.

  # uncomment below to test the property
  #expect_equal(model.instance$`revoke_detail`, "EXPECTED_RESULT")
})

test_that("schema_version", {
  # tests for the property `schema_version` (str)
  # The version of the JSON schema that the server uses to validate the object.

  # uncomment below to test the property
  #expect_equal(model.instance$`schema_version`, "EXPECTED_RESULT")
})

test_that("uuid", {
  # tests for the property `uuid` (str)
  # The unique identifier associated with every object.

  # uncomment below to test the property
  #expect_equal(model.instance$`uuid`, "EXPECTED_RESULT")
})

test_that("notes", {
  # tests for the property `notes` (str)
  # DACC internal notes.

  # uncomment below to test the property
  #expect_equal(model.instance$`notes`, "EXPECTED_RESULT")
})

test_that("aliases", {
  # tests for the property `aliases` (List[str])
  # Lab specific identifiers to reference an object.

  # uncomment below to test the property
  #expect_equal(model.instance$`aliases`, "EXPECTED_RESULT")
})

test_that("creation_timestamp", {
  # tests for the property `creation_timestamp` (str)
  # The date the object was created.

  # uncomment below to test the property
  #expect_equal(model.instance$`creation_timestamp`, "EXPECTED_RESULT")
})

test_that("submitted_by", {
  # tests for the property `submitted_by` (str)
  # The user who submitted the object.

  # uncomment below to test the property
  #expect_equal(model.instance$`submitted_by`, "EXPECTED_RESULT")
})

test_that("submitter_comment", {
  # tests for the property `submitter_comment` (str)
  # Additional information specified by the submitter to be displayed as a comment on the portal.

  # uncomment below to test the property
  #expect_equal(model.instance$`submitter_comment`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (str)
  # A plain text description of the object.

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("analysis_step_version", {
  # tests for the property `analysis_step_version` (str)
  # The analysis step version of the file.

  # uncomment below to test the property
  #expect_equal(model.instance$`analysis_step_version`, "EXPECTED_RESULT")
})

test_that("content_md5sum", {
  # tests for the property `content_md5sum` (str)
  # The MD5sum of the uncompressed file.

  # uncomment below to test the property
  #expect_equal(model.instance$`content_md5sum`, "EXPECTED_RESULT")
})

test_that("content_type", {
  # tests for the property `content_type` (str)
  # The type of content in the file.

  # uncomment below to test the property
  #expect_equal(model.instance$`content_type`, "EXPECTED_RESULT")
})

test_that("dbxrefs", {
  # tests for the property `dbxrefs` (List[str])
  # Identifiers from external resources that may have 1-to-1 or 1-to-many relationships with IGVF file objects.

  # uncomment below to test the property
  #expect_equal(model.instance$`dbxrefs`, "EXPECTED_RESULT")
})

test_that("derived_from", {
  # tests for the property `derived_from` (List[str])
  # The files participating as inputs into software to produce this output file.

  # uncomment below to test the property
  #expect_equal(model.instance$`derived_from`, "EXPECTED_RESULT")
})

test_that("file_format", {
  # tests for the property `file_format` (str)
  # The file format or extension of the file.

  # uncomment below to test the property
  #expect_equal(model.instance$`file_format`, "EXPECTED_RESULT")
})

test_that("file_format_specifications", {
  # tests for the property `file_format_specifications` (List[str])
  # Document that further explains the file format.

  # uncomment below to test the property
  #expect_equal(model.instance$`file_format_specifications`, "EXPECTED_RESULT")
})

test_that("file_set", {
  # tests for the property `file_set` (str)
  # The file set that this file belongs to.

  # uncomment below to test the property
  #expect_equal(model.instance$`file_set`, "EXPECTED_RESULT")
})

test_that("file_size", {
  # tests for the property `file_size` (int)
  # File size specified in bytes.

  # uncomment below to test the property
  #expect_equal(model.instance$`file_size`, "EXPECTED_RESULT")
})

test_that("md5sum", {
  # tests for the property `md5sum` (str)
  # The md5sum of the file being transferred.

  # uncomment below to test the property
  #expect_equal(model.instance$`md5sum`, "EXPECTED_RESULT")
})

test_that("submitted_file_name", {
  # tests for the property `submitted_file_name` (str)
  # Original name of the file.

  # uncomment below to test the property
  #expect_equal(model.instance$`submitted_file_name`, "EXPECTED_RESULT")
})

test_that("upload_status", {
  # tests for the property `upload_status` (str)
  # The upload/validation status of the file.

  # uncomment below to test the property
  #expect_equal(model.instance$`upload_status`, "EXPECTED_RESULT")
})

test_that("validation_error_detail", {
  # tests for the property `validation_error_detail` (str)
  # Explanation of why the file failed the automated content checks.

  # uncomment below to test the property
  #expect_equal(model.instance$`validation_error_detail`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (str)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (List[str])

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("summary", {
  # tests for the property `summary` (str)
  # A summary of the image file.

  # uncomment below to test the property
  #expect_equal(model.instance$`summary`, "EXPECTED_RESULT")
})

test_that("integrated_in", {
  # tests for the property `integrated_in` (List[str])
  # Construct library set(s) that this file was used for in insert design.

  # uncomment below to test the property
  #expect_equal(model.instance$`integrated_in`, "EXPECTED_RESULT")
})

test_that("input_file_for", {
  # tests for the property `input_file_for` (List[str])
  # The files which are derived from this file.

  # uncomment below to test the property
  #expect_equal(model.instance$`input_file_for`, "EXPECTED_RESULT")
})

test_that("gene_list_for", {
  # tests for the property `gene_list_for` (List[str])
  # File Set(s) that this file is a gene list for.

  # uncomment below to test the property
  #expect_equal(model.instance$`gene_list_for`, "EXPECTED_RESULT")
})

test_that("loci_list_for", {
  # tests for the property `loci_list_for` (List[str])
  # File Set(s) that this file is a loci list for.

  # uncomment below to test the property
  #expect_equal(model.instance$`loci_list_for`, "EXPECTED_RESULT")
})

test_that("href", {
  # tests for the property `href` (str)
  # The download path to obtain file.

  # uncomment below to test the property
  #expect_equal(model.instance$`href`, "EXPECTED_RESULT")
})

test_that("s3_uri", {
  # tests for the property `s3_uri` (str)
  # The S3 URI of public file object.

  # uncomment below to test the property
  #expect_equal(model.instance$`s3_uri`, "EXPECTED_RESULT")
})

test_that("upload_credentials", {
  # tests for the property `upload_credentials` (object)
  # The upload credentials for S3 to submit the file content.

  # uncomment below to test the property
  #expect_equal(model.instance$`upload_credentials`, "EXPECTED_RESULT")
})
