# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PageLayoutComponents")

model_instance <- PageLayoutComponents$new()

test_that("id", {
  # tests for the property `id` (str)
  # Unique identifier for this blocUnique identifier for this block.

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (str)
  # Indicates whether this block contains markdown or a component specification.

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("body", {
  # tests for the property `body` (str)
  # The text content of this block.

  # uncomment below to test the property
  #expect_equal(model.instance$`body`, "EXPECTED_RESULT")
})

test_that("direction", {
  # tests for the property `direction` (str)
  # The text language direction -- ltr or rtl.

  # uncomment below to test the property
  #expect_equal(model.instance$`direction`, "EXPECTED_RESULT")
})
