# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Gene")

model_instance <- Gene$new()

test_that("release_timestamp", {
  # tests for the property `release_timestamp` (str)
  # The date the object was released.

  # uncomment below to test the property
  #expect_equal(model.instance$`release_timestamp`, "EXPECTED_RESULT")
})

test_that("transcriptome_annotation", {
  # tests for the property `transcriptome_annotation` (str)
  # The annotation and version of the reference resource.

  # uncomment below to test the property
  #expect_equal(model.instance$`transcriptome_annotation`, "EXPECTED_RESULT")
})

test_that("taxa", {
  # tests for the property `taxa` (str)
  # The species of the organism.

  # uncomment below to test the property
  #expect_equal(model.instance$`taxa`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (str)
  # The status of the metadata object.

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("schema_version", {
  # tests for the property `schema_version` (str)
  # The version of the JSON schema that the server uses to validate the object.

  # uncomment below to test the property
  #expect_equal(model.instance$`schema_version`, "EXPECTED_RESULT")
})

test_that("uuid", {
  # tests for the property `uuid` (str)
  # The unique identifier associated with every object.

  # uncomment below to test the property
  #expect_equal(model.instance$`uuid`, "EXPECTED_RESULT")
})

test_that("notes", {
  # tests for the property `notes` (str)
  # DACC internal notes.

  # uncomment below to test the property
  #expect_equal(model.instance$`notes`, "EXPECTED_RESULT")
})

test_that("aliases", {
  # tests for the property `aliases` (List[str])
  # Lab specific identifiers to reference an object.

  # uncomment below to test the property
  #expect_equal(model.instance$`aliases`, "EXPECTED_RESULT")
})

test_that("creation_timestamp", {
  # tests for the property `creation_timestamp` (str)
  # The date the object was created.

  # uncomment below to test the property
  #expect_equal(model.instance$`creation_timestamp`, "EXPECTED_RESULT")
})

test_that("submitted_by", {
  # tests for the property `submitted_by` (str)
  # The user who submitted the object.

  # uncomment below to test the property
  #expect_equal(model.instance$`submitted_by`, "EXPECTED_RESULT")
})

test_that("submitter_comment", {
  # tests for the property `submitter_comment` (str)
  # Additional information specified by the submitter to be displayed as a comment on the portal.

  # uncomment below to test the property
  #expect_equal(model.instance$`submitter_comment`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (str)
  # A plain text description of the object.

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("geneid", {
  # tests for the property `geneid` (str)
  # ENSEMBL GeneID of official nomenclature approved gene. The GeneID does not include the current version number suffix.

  # uncomment below to test the property
  #expect_equal(model.instance$`geneid`, "EXPECTED_RESULT")
})

test_that("symbol", {
  # tests for the property `symbol` (str)
  # Gene symbol approved by the official nomenclature.

  # uncomment below to test the property
  #expect_equal(model.instance$`symbol`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (str)
  # The full gene name preferably approved by the official nomenclature.

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("synonyms", {
  # tests for the property `synonyms` (List[str])
  # Alternative symbols that have been used to refer to the gene.

  # uncomment below to test the property
  #expect_equal(model.instance$`synonyms`, "EXPECTED_RESULT")
})

test_that("dbxrefs", {
  # tests for the property `dbxrefs` (List[str])
  # Unique identifiers from external resources.

  # uncomment below to test the property
  #expect_equal(model.instance$`dbxrefs`, "EXPECTED_RESULT")
})

test_that("locations", {
  # tests for the property `locations` (List[GeneLocation1])
  # Gene locations specified using 1-based, closed coordinates for different versions of reference genome assemblies.

  # uncomment below to test the property
  #expect_equal(model.instance$`locations`, "EXPECTED_RESULT")
})

test_that("version_number", {
  # tests for the property `version_number` (str)
  # Current ENSEMBL GeneID version number of the gene.

  # uncomment below to test the property
  #expect_equal(model.instance$`version_number`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (str)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (List[str])

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("summary", {
  # tests for the property `summary` (str)

  # uncomment below to test the property
  #expect_equal(model.instance$`summary`, "EXPECTED_RESULT")
})

test_that("title", {
  # tests for the property `title` (str)

  # uncomment below to test the property
  #expect_equal(model.instance$`title`, "EXPECTED_RESULT")
})

test_that("geneid_with_version", {
  # tests for the property `geneid_with_version` (str)
  # The ENSEMBL GeneID concatenated with its version number.

  # uncomment below to test the property
  #expect_equal(model.instance$`geneid_with_version`, "EXPECTED_RESULT")
})
