# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InVitroSystem")

model_instance <- InVitroSystem$new()

test_that("release_timestamp", {
  # tests for the property `release_timestamp` (str)
  # The date the object was released.

  # uncomment below to test the property
  #expect_equal(model.instance$`release_timestamp`, "EXPECTED_RESULT")
})

test_that("publications", {
  # tests for the property `publications` (List[str])
  # The publications associated with this object.

  # uncomment below to test the property
  #expect_equal(model.instance$`publications`, "EXPECTED_RESULT")
})

test_that("taxa", {
  # tests for the property `taxa` (str)
  # The species of the organism.

  # uncomment below to test the property
  #expect_equal(model.instance$`taxa`, "EXPECTED_RESULT")
})

test_that("url", {
  # tests for the property `url` (str)
  # An external resource with additional information.

  # uncomment below to test the property
  #expect_equal(model.instance$`url`, "EXPECTED_RESULT")
})

test_that("sources", {
  # tests for the property `sources` (List[str])
  # The originating lab(s) or vendor(s).

  # uncomment below to test the property
  #expect_equal(model.instance$`sources`, "EXPECTED_RESULT")
})

test_that("lot_id", {
  # tests for the property `lot_id` (str)
  # The lot identifier provided by the originating lab or vendor.

  # uncomment below to test the property
  #expect_equal(model.instance$`lot_id`, "EXPECTED_RESULT")
})

test_that("product_id", {
  # tests for the property `product_id` (str)
  # The product identifier provided by the originating lab or vendor.

  # uncomment below to test the property
  #expect_equal(model.instance$`product_id`, "EXPECTED_RESULT")
})

test_that("documents", {
  # tests for the property `documents` (List[str])
  # Documents that provide additional information (not data file).

  # uncomment below to test the property
  #expect_equal(model.instance$`documents`, "EXPECTED_RESULT")
})

test_that("lab", {
  # tests for the property `lab` (str)
  # Lab associated with the submission.

  # uncomment below to test the property
  #expect_equal(model.instance$`lab`, "EXPECTED_RESULT")
})

test_that("award", {
  # tests for the property `award` (str)
  # Grant associated with the submission.

  # uncomment below to test the property
  #expect_equal(model.instance$`award`, "EXPECTED_RESULT")
})

test_that("accession", {
  # tests for the property `accession` (str)
  # A unique identifier to be used to reference the object prefixed with IGVF.

  # uncomment below to test the property
  #expect_equal(model.instance$`accession`, "EXPECTED_RESULT")
})

test_that("alternate_accessions", {
  # tests for the property `alternate_accessions` (List[str])
  # Accessions previously assigned to objects that have been merged with this object.

  # uncomment below to test the property
  #expect_equal(model.instance$`alternate_accessions`, "EXPECTED_RESULT")
})

test_that("collections", {
  # tests for the property `collections` (List[str])
  # Some samples are part of particular data collections.

  # uncomment below to test the property
  #expect_equal(model.instance$`collections`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (str)
  # The status of the metadata object.

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("revoke_detail", {
  # tests for the property `revoke_detail` (str)
  # Explanation of why an object was transitioned to the revoked status.

  # uncomment below to test the property
  #expect_equal(model.instance$`revoke_detail`, "EXPECTED_RESULT")
})

test_that("schema_version", {
  # tests for the property `schema_version` (str)
  # The version of the JSON schema that the server uses to validate the object.

  # uncomment below to test the property
  #expect_equal(model.instance$`schema_version`, "EXPECTED_RESULT")
})

test_that("uuid", {
  # tests for the property `uuid` (str)
  # The unique identifier associated with every object.

  # uncomment below to test the property
  #expect_equal(model.instance$`uuid`, "EXPECTED_RESULT")
})

test_that("notes", {
  # tests for the property `notes` (str)
  # DACC internal notes.

  # uncomment below to test the property
  #expect_equal(model.instance$`notes`, "EXPECTED_RESULT")
})

test_that("aliases", {
  # tests for the property `aliases` (List[str])
  # Lab specific identifiers to reference an object.

  # uncomment below to test the property
  #expect_equal(model.instance$`aliases`, "EXPECTED_RESULT")
})

test_that("creation_timestamp", {
  # tests for the property `creation_timestamp` (str)
  # The date the object was created.

  # uncomment below to test the property
  #expect_equal(model.instance$`creation_timestamp`, "EXPECTED_RESULT")
})

test_that("submitted_by", {
  # tests for the property `submitted_by` (str)
  # The user who submitted the object.

  # uncomment below to test the property
  #expect_equal(model.instance$`submitted_by`, "EXPECTED_RESULT")
})

test_that("submitter_comment", {
  # tests for the property `submitter_comment` (str)
  # Additional information specified by the submitter to be displayed as a comment on the portal.

  # uncomment below to test the property
  #expect_equal(model.instance$`submitter_comment`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (str)
  # A plain text description of the object.

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("lower_bound_age", {
  # tests for the property `lower_bound_age` (float)
  # Lower bound of age of the organism at the time of collection of the sample.

  # uncomment below to test the property
  #expect_equal(model.instance$`lower_bound_age`, "EXPECTED_RESULT")
})

test_that("upper_bound_age", {
  # tests for the property `upper_bound_age` (float)
  # Upper bound of age of the organism at the time of collection of the sample.

  # uncomment below to test the property
  #expect_equal(model.instance$`upper_bound_age`, "EXPECTED_RESULT")
})

test_that("age_units", {
  # tests for the property `age_units` (str)
  # The units of time associated with age of the biosample.

  # uncomment below to test the property
  #expect_equal(model.instance$`age_units`, "EXPECTED_RESULT")
})

test_that("sample_terms", {
  # tests for the property `sample_terms` (List[str])
  # Ontology terms identifying a biosample.

  # uncomment below to test the property
  #expect_equal(model.instance$`sample_terms`, "EXPECTED_RESULT")
})

test_that("disease_terms", {
  # tests for the property `disease_terms` (List[str])
  # Ontology term of the disease associated with the biosample.

  # uncomment below to test the property
  #expect_equal(model.instance$`disease_terms`, "EXPECTED_RESULT")
})

test_that("pooled_from", {
  # tests for the property `pooled_from` (List[str])
  # The biosamples this biosample is pooled from.

  # uncomment below to test the property
  #expect_equal(model.instance$`pooled_from`, "EXPECTED_RESULT")
})

test_that("part_of", {
  # tests for the property `part_of` (str)
  # Links to a biosample which represents a larger sample from which this sample was taken regardless of whether it is a tissue taken from an organism or smaller slices of a piece of tissue or aliquots of a cell growth.

  # uncomment below to test the property
  #expect_equal(model.instance$`part_of`, "EXPECTED_RESULT")
})

test_that("originated_from", {
  # tests for the property `originated_from` (str)
  # Links to a biosample that was originated from due to differentiation, dedifferentiation, reprogramming, or the introduction of a genetic modification.

  # uncomment below to test the property
  #expect_equal(model.instance$`originated_from`, "EXPECTED_RESULT")
})

test_that("treatments", {
  # tests for the property `treatments` (List[str])
  # A list of treatments applied to the biosample with the purpose of perturbation.

  # uncomment below to test the property
  #expect_equal(model.instance$`treatments`, "EXPECTED_RESULT")
})

test_that("donors", {
  # tests for the property `donors` (List[str])
  # Donor(s) the sample was derived from.

  # uncomment below to test the property
  #expect_equal(model.instance$`donors`, "EXPECTED_RESULT")
})

test_that("biomarkers", {
  # tests for the property `biomarkers` (List[str])
  # Biological markers that are associated with this sample.

  # uncomment below to test the property
  #expect_equal(model.instance$`biomarkers`, "EXPECTED_RESULT")
})

test_that("embryonic", {
  # tests for the property `embryonic` (bool)
  # Biosample is embryonic.

  # uncomment below to test the property
  #expect_equal(model.instance$`embryonic`, "EXPECTED_RESULT")
})

test_that("modifications", {
  # tests for the property `modifications` (List[str])
  # Links to modifications applied to this biosample.

  # uncomment below to test the property
  #expect_equal(model.instance$`modifications`, "EXPECTED_RESULT")
})

test_that("cellular_sub_pool", {
  # tests for the property `cellular_sub_pool` (str)
  # Cellular sub-pool fraction of the sample. Also known as PKR and sub-library.

  # uncomment below to test the property
  #expect_equal(model.instance$`cellular_sub_pool`, "EXPECTED_RESULT")
})

test_that("starting_amount", {
  # tests for the property `starting_amount` (float)
  # The initial quantity of samples obtained.

  # uncomment below to test the property
  #expect_equal(model.instance$`starting_amount`, "EXPECTED_RESULT")
})

test_that("starting_amount_units", {
  # tests for the property `starting_amount_units` (str)
  # The units used to quantify the amount of samples obtained.

  # uncomment below to test the property
  #expect_equal(model.instance$`starting_amount_units`, "EXPECTED_RESULT")
})

test_that("dbxrefs", {
  # tests for the property `dbxrefs` (List[str])
  # Biosample identifiers from external resources, such as Biosample database or Cellosaurus.

  # uncomment below to test the property
  #expect_equal(model.instance$`dbxrefs`, "EXPECTED_RESULT")
})

test_that("date_obtained", {
  # tests for the property `date_obtained` (str)
  # The date the sample was harvested, dissected or created, depending on the type of the sample.

  # uncomment below to test the property
  #expect_equal(model.instance$`date_obtained`, "EXPECTED_RESULT")
})

test_that("sorted_from", {
  # tests for the property `sorted_from` (str)
  # Links to a larger sample from which this sample was obtained through sorting.

  # uncomment below to test the property
  #expect_equal(model.instance$`sorted_from`, "EXPECTED_RESULT")
})

test_that("sorted_from_detail", {
  # tests for the property `sorted_from_detail` (str)
  # Detail for sample sorted into fractions capturing information about sorting.

  # uncomment below to test the property
  #expect_equal(model.instance$`sorted_from_detail`, "EXPECTED_RESULT")
})

test_that("virtual", {
  # tests for the property `virtual` (bool)
  # Virtual samples are not representing actual physical entities from experiments, but rather capturing metadata about hypothetical samples that the reported analysis results are relevant for.

  # uncomment below to test the property
  #expect_equal(model.instance$`virtual`, "EXPECTED_RESULT")
})

test_that("construct_library_sets", {
  # tests for the property `construct_library_sets` (List[str])
  # The construct library sets of vectors introduced to this sample prior to performing an assay.

  # uncomment below to test the property
  #expect_equal(model.instance$`construct_library_sets`, "EXPECTED_RESULT")
})

test_that("moi", {
  # tests for the property `moi` (float)
  # The actual multiplicity of infection (MOI) for vectors introduced to this sample. At least one construct library set must be specified in order to specify MOI. This property should capture the actual MOI, and not the targeted MOI.

  # uncomment below to test the property
  #expect_equal(model.instance$`moi`, "EXPECTED_RESULT")
})

test_that("nucleic_acid_delivery", {
  # tests for the property `nucleic_acid_delivery` (str)
  # Method of introduction of nucleic acid into the cell.

  # uncomment below to test the property
  #expect_equal(model.instance$`nucleic_acid_delivery`, "EXPECTED_RESULT")
})

test_that("time_post_library_delivery", {
  # tests for the property `time_post_library_delivery` (float)
  # The time that elapsed past the time-point when the construct library sets were introduced.

  # uncomment below to test the property
  #expect_equal(model.instance$`time_post_library_delivery`, "EXPECTED_RESULT")
})

test_that("time_post_library_delivery_units", {
  # tests for the property `time_post_library_delivery_units` (str)
  # The units of time that elapsed past the point when the construct library sets were introduced.

  # uncomment below to test the property
  #expect_equal(model.instance$`time_post_library_delivery_units`, "EXPECTED_RESULT")
})

test_that("protocols", {
  # tests for the property `protocols` (List[str])
  # Links to the protocol(s) for preparing the samples on Protocols.io.

  # uncomment below to test the property
  #expect_equal(model.instance$`protocols`, "EXPECTED_RESULT")
})

test_that("classifications", {
  # tests for the property `classifications` (List[str])
  # The general category of this type of in vitro system.

  # uncomment below to test the property
  #expect_equal(model.instance$`classifications`, "EXPECTED_RESULT")
})

test_that("time_post_change", {
  # tests for the property `time_post_change` (float)
  # The time that elapsed past the time-point when the cell fate change treatments were introduced.

  # uncomment below to test the property
  #expect_equal(model.instance$`time_post_change`, "EXPECTED_RESULT")
})

test_that("time_post_change_units", {
  # tests for the property `time_post_change_units` (str)
  # The units of time that elapsed past the point when the cell fate change treatments were introduced.

  # uncomment below to test the property
  #expect_equal(model.instance$`time_post_change_units`, "EXPECTED_RESULT")
})

test_that("cell_fate_change_treatments", {
  # tests for the property `cell_fate_change_treatments` (List[str])
  # A list of treatments applied to the biosample with the purpose of differentiation, dedifferentiation, or reprogramming.

  # uncomment below to test the property
  #expect_equal(model.instance$`cell_fate_change_treatments`, "EXPECTED_RESULT")
})

test_that("cell_fate_change_protocol", {
  # tests for the property `cell_fate_change_protocol` (str)
  # A protocol applied to the biosample with the purpose of differentiation, dedifferentiation, or reprogramming.

  # uncomment below to test the property
  #expect_equal(model.instance$`cell_fate_change_protocol`, "EXPECTED_RESULT")
})

test_that("demultiplexed_from", {
  # tests for the property `demultiplexed_from` (str)
  # The biosample this in vitro system sample was demultiplexed from using computational methods.

  # uncomment below to test the property
  #expect_equal(model.instance$`demultiplexed_from`, "EXPECTED_RESULT")
})

test_that("passage_number", {
  # tests for the property `passage_number` (int)
  # Number of passages including the passages from the source.

  # uncomment below to test the property
  #expect_equal(model.instance$`passage_number`, "EXPECTED_RESULT")
})

test_that("targeted_sample_term", {
  # tests for the property `targeted_sample_term` (str)
  # Ontology term identifying the targeted endpoint biosample resulting from differentation or reprogramming.

  # uncomment below to test the property
  #expect_equal(model.instance$`targeted_sample_term`, "EXPECTED_RESULT")
})

test_that("growth_medium", {
  # tests for the property `growth_medium` (str)
  # A growth medium of the in vitro system.

  # uncomment below to test the property
  #expect_equal(model.instance$`growth_medium`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (str)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (List[str])

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("summary", {
  # tests for the property `summary` (str)
  # A summary of the sample.

  # uncomment below to test the property
  #expect_equal(model.instance$`summary`, "EXPECTED_RESULT")
})

test_that("file_sets", {
  # tests for the property `file_sets` (List[str])
  # The file sets linked to this sample.

  # uncomment below to test the property
  #expect_equal(model.instance$`file_sets`, "EXPECTED_RESULT")
})

test_that("multiplexed_in", {
  # tests for the property `multiplexed_in` (List[str])
  # The multiplexed samples in which this sample is included.

  # uncomment below to test the property
  #expect_equal(model.instance$`multiplexed_in`, "EXPECTED_RESULT")
})

test_that("sorted_fractions", {
  # tests for the property `sorted_fractions` (List[str])
  # The fractions into which this sample has been sorted.

  # uncomment below to test the property
  #expect_equal(model.instance$`sorted_fractions`, "EXPECTED_RESULT")
})

test_that("origin_of", {
  # tests for the property `origin_of` (List[str])
  # The samples which originate from this sample, such as through a process of cell differentiation.

  # uncomment below to test the property
  #expect_equal(model.instance$`origin_of`, "EXPECTED_RESULT")
})

test_that("institutional_certificates", {
  # tests for the property `institutional_certificates` (List[str])
  # The institutional certificates under which use of this sample is approved.

  # uncomment below to test the property
  #expect_equal(model.instance$`institutional_certificates`, "EXPECTED_RESULT")
})

test_that("sex", {
  # tests for the property `sex` (str)

  # uncomment below to test the property
  #expect_equal(model.instance$`sex`, "EXPECTED_RESULT")
})

test_that("age", {
  # tests for the property `age` (str)
  # Age of organism at the time of collection of the sample.

  # uncomment below to test the property
  #expect_equal(model.instance$`age`, "EXPECTED_RESULT")
})

test_that("upper_bound_age_in_hours", {
  # tests for the property `upper_bound_age_in_hours` (float)
  # Upper bound of age of organism in hours at the time of collection of the sample.

  # uncomment below to test the property
  #expect_equal(model.instance$`upper_bound_age_in_hours`, "EXPECTED_RESULT")
})

test_that("lower_bound_age_in_hours", {
  # tests for the property `lower_bound_age_in_hours` (float)
  # Lower bound of age of organism in hours at the time of collection of the sample .

  # uncomment below to test the property
  #expect_equal(model.instance$`lower_bound_age_in_hours`, "EXPECTED_RESULT")
})

test_that("parts", {
  # tests for the property `parts` (List[str])
  # The parts into which this sample has been divided.

  # uncomment below to test the property
  #expect_equal(model.instance$`parts`, "EXPECTED_RESULT")
})

test_that("pooled_in", {
  # tests for the property `pooled_in` (List[str])
  # The pooled samples in which this sample is included.

  # uncomment below to test the property
  #expect_equal(model.instance$`pooled_in`, "EXPECTED_RESULT")
})

test_that("demultiplexed_to", {
  # tests for the property `demultiplexed_to` (List[str])
  # The parts into which this sample has been demultiplexed.

  # uncomment below to test the property
  #expect_equal(model.instance$`demultiplexed_to`, "EXPECTED_RESULT")
})
