# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MeasurementSet")

model_instance <- MeasurementSet$new()

test_that("release_timestamp", {
  # tests for the property `release_timestamp` (str)
  # The date the object was released.

  # uncomment below to test the property
  #expect_equal(model.instance$`release_timestamp`, "EXPECTED_RESULT")
})

test_that("publications", {
  # tests for the property `publications` (List[str])
  # The publications associated with this object.

  # uncomment below to test the property
  #expect_equal(model.instance$`publications`, "EXPECTED_RESULT")
})

test_that("documents", {
  # tests for the property `documents` (List[str])
  # Documents that provide additional information (not data file).

  # uncomment below to test the property
  #expect_equal(model.instance$`documents`, "EXPECTED_RESULT")
})

test_that("lab", {
  # tests for the property `lab` (str)
  # Lab associated with the submission.

  # uncomment below to test the property
  #expect_equal(model.instance$`lab`, "EXPECTED_RESULT")
})

test_that("award", {
  # tests for the property `award` (str)
  # Grant associated with the submission.

  # uncomment below to test the property
  #expect_equal(model.instance$`award`, "EXPECTED_RESULT")
})

test_that("accession", {
  # tests for the property `accession` (str)
  # A unique identifier to be used to reference the object prefixed with IGVF.

  # uncomment below to test the property
  #expect_equal(model.instance$`accession`, "EXPECTED_RESULT")
})

test_that("alternate_accessions", {
  # tests for the property `alternate_accessions` (List[str])
  # Accessions previously assigned to objects that have been merged with this object.

  # uncomment below to test the property
  #expect_equal(model.instance$`alternate_accessions`, "EXPECTED_RESULT")
})

test_that("collections", {
  # tests for the property `collections` (List[str])
  # Some samples are part of particular data collections.

  # uncomment below to test the property
  #expect_equal(model.instance$`collections`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (str)
  # The status of the metadata object.

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("revoke_detail", {
  # tests for the property `revoke_detail` (str)
  # Explanation of why an object was transitioned to the revoked status.

  # uncomment below to test the property
  #expect_equal(model.instance$`revoke_detail`, "EXPECTED_RESULT")
})

test_that("schema_version", {
  # tests for the property `schema_version` (str)
  # The version of the JSON schema that the server uses to validate the object.

  # uncomment below to test the property
  #expect_equal(model.instance$`schema_version`, "EXPECTED_RESULT")
})

test_that("uuid", {
  # tests for the property `uuid` (str)
  # The unique identifier associated with every object.

  # uncomment below to test the property
  #expect_equal(model.instance$`uuid`, "EXPECTED_RESULT")
})

test_that("notes", {
  # tests for the property `notes` (str)
  # DACC internal notes.

  # uncomment below to test the property
  #expect_equal(model.instance$`notes`, "EXPECTED_RESULT")
})

test_that("aliases", {
  # tests for the property `aliases` (List[str])
  # Lab specific identifiers to reference an object.

  # uncomment below to test the property
  #expect_equal(model.instance$`aliases`, "EXPECTED_RESULT")
})

test_that("creation_timestamp", {
  # tests for the property `creation_timestamp` (str)
  # The date the object was created.

  # uncomment below to test the property
  #expect_equal(model.instance$`creation_timestamp`, "EXPECTED_RESULT")
})

test_that("submitted_by", {
  # tests for the property `submitted_by` (str)
  # The user who submitted the object.

  # uncomment below to test the property
  #expect_equal(model.instance$`submitted_by`, "EXPECTED_RESULT")
})

test_that("submitter_comment", {
  # tests for the property `submitter_comment` (str)
  # Additional information specified by the submitter to be displayed as a comment on the portal.

  # uncomment below to test the property
  #expect_equal(model.instance$`submitter_comment`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (str)
  # A plain text description of the object.

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("dbxrefs", {
  # tests for the property `dbxrefs` (List[str])
  # Identifiers from external resources that may have 1-to-1 or 1-to-many relationships with IGVF file sets.

  # uncomment below to test the property
  #expect_equal(model.instance$`dbxrefs`, "EXPECTED_RESULT")
})

test_that("samples", {
  # tests for the property `samples` (List[str])
  # The sample(s) associated with this file set.

  # uncomment below to test the property
  #expect_equal(model.instance$`samples`, "EXPECTED_RESULT")
})

test_that("donors", {
  # tests for the property `donors` (List[str])
  # The donors of the samples associated with this measurement set.

  # uncomment below to test the property
  #expect_equal(model.instance$`donors`, "EXPECTED_RESULT")
})

test_that("file_set_type", {
  # tests for the property `file_set_type` (str)
  # The category that best describes this measurement set.

  # uncomment below to test the property
  #expect_equal(model.instance$`file_set_type`, "EXPECTED_RESULT")
})

test_that("assay_term", {
  # tests for the property `assay_term` (str)
  # The assay used to produce data in this measurement set.

  # uncomment below to test the property
  #expect_equal(model.instance$`assay_term`, "EXPECTED_RESULT")
})

test_that("protocols", {
  # tests for the property `protocols` (List[str])
  # Links to the protocol(s) for conducting the assay on Protocols.io.

  # uncomment below to test the property
  #expect_equal(model.instance$`protocols`, "EXPECTED_RESULT")
})

test_that("preferred_assay_title", {
  # tests for the property `preferred_assay_title` (str)
  # The custom lab preferred label for the experiment performed in this measurement set.

  # uncomment below to test the property
  #expect_equal(model.instance$`preferred_assay_title`, "EXPECTED_RESULT")
})

test_that("multiome_size", {
  # tests for the property `multiome_size` (int)
  # The number of datasets included in the multiome experiment this measurement set is a part of.

  # uncomment below to test the property
  #expect_equal(model.instance$`multiome_size`, "EXPECTED_RESULT")
})

test_that("control_file_sets", {
  # tests for the property `control_file_sets` (List[str])
  # File sets that can serve as scientific controls for this measurement_set.

  # uncomment below to test the property
  #expect_equal(model.instance$`control_file_sets`, "EXPECTED_RESULT")
})

test_that("sequencing_library_types", {
  # tests for the property `sequencing_library_types` (List[str])
  # Description of the libraries sequenced in this measurement set.

  # uncomment below to test the property
  #expect_equal(model.instance$`sequencing_library_types`, "EXPECTED_RESULT")
})

test_that("auxiliary_sets", {
  # tests for the property `auxiliary_sets` (List[str])
  # The auxiliary sets of files produced alongside raw data from this measurement set.

  # uncomment below to test the property
  #expect_equal(model.instance$`auxiliary_sets`, "EXPECTED_RESULT")
})

test_that("external_image_url", {
  # tests for the property `external_image_url` (str)
  # Links to the external site where images produced by this measurement are stored.

  # uncomment below to test the property
  #expect_equal(model.instance$`external_image_url`, "EXPECTED_RESULT")
})

test_that("targeted_genes", {
  # tests for the property `targeted_genes` (List[str])
  # A list of genes targeted in this assay. For example, TF ChIP-seq attempts to identify binding sites of a protein encoded by a specific gene. In CRISPR FlowFISH, the modified samples are sorted based on expression of a specific gene. This property differs from small_scale_gene_list in Construct Library Set, which describes genes targeted by the content integrated in the constructs (such as guide RNAs.)

  # uncomment below to test the property
  #expect_equal(model.instance$`targeted_genes`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (str)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (List[str])

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("summary", {
  # tests for the property `summary` (str)

  # uncomment below to test the property
  #expect_equal(model.instance$`summary`, "EXPECTED_RESULT")
})

test_that("files", {
  # tests for the property `files` (List[str])
  # The files associated with this file set.

  # uncomment below to test the property
  #expect_equal(model.instance$`files`, "EXPECTED_RESULT")
})

test_that("control_for", {
  # tests for the property `control_for` (List[str])
  # The file sets for which this file set is a control.

  # uncomment below to test the property
  #expect_equal(model.instance$`control_for`, "EXPECTED_RESULT")
})

test_that("submitted_files_timestamp", {
  # tests for the property `submitted_files_timestamp` (str)
  # The timestamp the first file object in the file_set or associated auxiliary sets was created.

  # uncomment below to test the property
  #expect_equal(model.instance$`submitted_files_timestamp`, "EXPECTED_RESULT")
})

test_that("input_file_set_for", {
  # tests for the property `input_file_set_for` (List[str])
  # The file sets that use this file set as an input.

  # uncomment below to test the property
  #expect_equal(model.instance$`input_file_set_for`, "EXPECTED_RESULT")
})

test_that("related_multiome_datasets", {
  # tests for the property `related_multiome_datasets` (List[str])
  # Related datasets included in the multiome experiment this measurement set is a part of.

  # uncomment below to test the property
  #expect_equal(model.instance$`related_multiome_datasets`, "EXPECTED_RESULT")
})
