# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SequenceFile")

model_instance <- SequenceFile$new()

test_that("controlled_access", {
  # tests for the property `controlled_access` (bool)
  # Boolean value, indicating the file being controlled access, if true.

  # uncomment below to test the property
  #expect_equal(model.instance$`controlled_access`, "EXPECTED_RESULT")
})

test_that("anvil_url", {
  # tests for the property `anvil_url` (str)
  # URL linking to the controlled access file that has been deposited at AnVIL workspace.

  # uncomment below to test the property
  #expect_equal(model.instance$`anvil_url`, "EXPECTED_RESULT")
})

test_that("release_timestamp", {
  # tests for the property `release_timestamp` (str)
  # The date the object was released.

  # uncomment below to test the property
  #expect_equal(model.instance$`release_timestamp`, "EXPECTED_RESULT")
})

test_that("documents", {
  # tests for the property `documents` (List[str])
  # Documents that provide additional information (not data file).

  # uncomment below to test the property
  #expect_equal(model.instance$`documents`, "EXPECTED_RESULT")
})

test_that("lab", {
  # tests for the property `lab` (str)
  # Lab associated with the submission.

  # uncomment below to test the property
  #expect_equal(model.instance$`lab`, "EXPECTED_RESULT")
})

test_that("award", {
  # tests for the property `award` (str)
  # Grant associated with the submission.

  # uncomment below to test the property
  #expect_equal(model.instance$`award`, "EXPECTED_RESULT")
})

test_that("accession", {
  # tests for the property `accession` (str)
  # A unique identifier to be used to reference the object prefixed with IGVF.

  # uncomment below to test the property
  #expect_equal(model.instance$`accession`, "EXPECTED_RESULT")
})

test_that("alternate_accessions", {
  # tests for the property `alternate_accessions` (List[str])
  # Accessions previously assigned to objects that have been merged with this object.

  # uncomment below to test the property
  #expect_equal(model.instance$`alternate_accessions`, "EXPECTED_RESULT")
})

test_that("collections", {
  # tests for the property `collections` (List[str])
  # Some samples are part of particular data collections.

  # uncomment below to test the property
  #expect_equal(model.instance$`collections`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (str)
  # The status of the metadata object.

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("revoke_detail", {
  # tests for the property `revoke_detail` (str)
  # Explanation of why an object was transitioned to the revoked status.

  # uncomment below to test the property
  #expect_equal(model.instance$`revoke_detail`, "EXPECTED_RESULT")
})

test_that("schema_version", {
  # tests for the property `schema_version` (str)
  # The version of the JSON schema that the server uses to validate the object.

  # uncomment below to test the property
  #expect_equal(model.instance$`schema_version`, "EXPECTED_RESULT")
})

test_that("uuid", {
  # tests for the property `uuid` (str)
  # The unique identifier associated with every object.

  # uncomment below to test the property
  #expect_equal(model.instance$`uuid`, "EXPECTED_RESULT")
})

test_that("notes", {
  # tests for the property `notes` (str)
  # DACC internal notes.

  # uncomment below to test the property
  #expect_equal(model.instance$`notes`, "EXPECTED_RESULT")
})

test_that("aliases", {
  # tests for the property `aliases` (List[str])
  # Lab specific identifiers to reference an object.

  # uncomment below to test the property
  #expect_equal(model.instance$`aliases`, "EXPECTED_RESULT")
})

test_that("creation_timestamp", {
  # tests for the property `creation_timestamp` (str)
  # The date the object was created.

  # uncomment below to test the property
  #expect_equal(model.instance$`creation_timestamp`, "EXPECTED_RESULT")
})

test_that("submitted_by", {
  # tests for the property `submitted_by` (str)
  # The user who submitted the object.

  # uncomment below to test the property
  #expect_equal(model.instance$`submitted_by`, "EXPECTED_RESULT")
})

test_that("submitter_comment", {
  # tests for the property `submitter_comment` (str)
  # Additional information specified by the submitter to be displayed as a comment on the portal.

  # uncomment below to test the property
  #expect_equal(model.instance$`submitter_comment`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (str)
  # A plain text description of the object.

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("analysis_step_version", {
  # tests for the property `analysis_step_version` (str)
  # The analysis step version of the file.

  # uncomment below to test the property
  #expect_equal(model.instance$`analysis_step_version`, "EXPECTED_RESULT")
})

test_that("content_md5sum", {
  # tests for the property `content_md5sum` (str)
  # The MD5sum of the uncompressed file.

  # uncomment below to test the property
  #expect_equal(model.instance$`content_md5sum`, "EXPECTED_RESULT")
})

test_that("content_type", {
  # tests for the property `content_type` (str)
  # The type of content in the file.

  # uncomment below to test the property
  #expect_equal(model.instance$`content_type`, "EXPECTED_RESULT")
})

test_that("dbxrefs", {
  # tests for the property `dbxrefs` (List[str])
  # Identifiers from external resources that may have 1-to-1 or 1-to-many relationships with IGVF file objects.

  # uncomment below to test the property
  #expect_equal(model.instance$`dbxrefs`, "EXPECTED_RESULT")
})

test_that("derived_from", {
  # tests for the property `derived_from` (List[str])
  # The files participating as inputs into software to produce this output file.

  # uncomment below to test the property
  #expect_equal(model.instance$`derived_from`, "EXPECTED_RESULT")
})

test_that("file_format", {
  # tests for the property `file_format` (str)
  # The file format or extension of the file.

  # uncomment below to test the property
  #expect_equal(model.instance$`file_format`, "EXPECTED_RESULT")
})

test_that("file_format_specifications", {
  # tests for the property `file_format_specifications` (List[str])
  # Document that further explains the file format.

  # uncomment below to test the property
  #expect_equal(model.instance$`file_format_specifications`, "EXPECTED_RESULT")
})

test_that("file_set", {
  # tests for the property `file_set` (str)
  # The file set that this file belongs to.

  # uncomment below to test the property
  #expect_equal(model.instance$`file_set`, "EXPECTED_RESULT")
})

test_that("file_size", {
  # tests for the property `file_size` (int)
  # File size specified in bytes.

  # uncomment below to test the property
  #expect_equal(model.instance$`file_size`, "EXPECTED_RESULT")
})

test_that("md5sum", {
  # tests for the property `md5sum` (str)
  # The md5sum of the file being transferred.

  # uncomment below to test the property
  #expect_equal(model.instance$`md5sum`, "EXPECTED_RESULT")
})

test_that("submitted_file_name", {
  # tests for the property `submitted_file_name` (str)
  # Original name of the file.

  # uncomment below to test the property
  #expect_equal(model.instance$`submitted_file_name`, "EXPECTED_RESULT")
})

test_that("upload_status", {
  # tests for the property `upload_status` (str)
  # The upload/validation status of the file.

  # uncomment below to test the property
  #expect_equal(model.instance$`upload_status`, "EXPECTED_RESULT")
})

test_that("validation_error_detail", {
  # tests for the property `validation_error_detail` (str)
  # Explanation of why the file failed the automated content checks.

  # uncomment below to test the property
  #expect_equal(model.instance$`validation_error_detail`, "EXPECTED_RESULT")
})

test_that("flowcell_id", {
  # tests for the property `flowcell_id` (str)
  # The alphanumeric identifier for the flowcell of a sequencing machine.

  # uncomment below to test the property
  #expect_equal(model.instance$`flowcell_id`, "EXPECTED_RESULT")
})

test_that("lane", {
  # tests for the property `lane` (int)
  # An integer identifying the lane of a sequencing machine.

  # uncomment below to test the property
  #expect_equal(model.instance$`lane`, "EXPECTED_RESULT")
})

test_that("read_count", {
  # tests for the property `read_count` (int)
  # Number of reads in a fastq file.

  # uncomment below to test the property
  #expect_equal(model.instance$`read_count`, "EXPECTED_RESULT")
})

test_that("minimum_read_length", {
  # tests for the property `minimum_read_length` (int)
  # For high-throughput sequencing, the minimum number of contiguous nucleotides determined by sequencing.

  # uncomment below to test the property
  #expect_equal(model.instance$`minimum_read_length`, "EXPECTED_RESULT")
})

test_that("maximum_read_length", {
  # tests for the property `maximum_read_length` (int)
  # For high-throughput sequencing, the maximum number of contiguous nucleotides determined by sequencing.

  # uncomment below to test the property
  #expect_equal(model.instance$`maximum_read_length`, "EXPECTED_RESULT")
})

test_that("mean_read_length", {
  # tests for the property `mean_read_length` (float)
  # For high-throughput sequencing, the mean number of contiguous nucleotides determined by sequencing.

  # uncomment below to test the property
  #expect_equal(model.instance$`mean_read_length`, "EXPECTED_RESULT")
})

test_that("sequencing_platform", {
  # tests for the property `sequencing_platform` (str)
  # The measurement device used to produce sequencing data.

  # uncomment below to test the property
  #expect_equal(model.instance$`sequencing_platform`, "EXPECTED_RESULT")
})

test_that("sequencing_kit", {
  # tests for the property `sequencing_kit` (str)
  # A reagent kit used with a library to prepare it for sequencing.

  # uncomment below to test the property
  #expect_equal(model.instance$`sequencing_kit`, "EXPECTED_RESULT")
})

test_that("sequencing_run", {
  # tests for the property `sequencing_run` (int)
  # An ordinal number indicating which sequencing run of the associated library that the file belongs to.

  # uncomment below to test the property
  #expect_equal(model.instance$`sequencing_run`, "EXPECTED_RESULT")
})

test_that("illumina_read_type", {
  # tests for the property `illumina_read_type` (str)
  # The read type of the file. Relevant only for files produced using an Illumina sequencing platform.

  # uncomment below to test the property
  #expect_equal(model.instance$`illumina_read_type`, "EXPECTED_RESULT")
})

test_that("index", {
  # tests for the property `index` (str)
  # An Illumina index associated with the file.

  # uncomment below to test the property
  #expect_equal(model.instance$`index`, "EXPECTED_RESULT")
})

test_that("base_modifications", {
  # tests for the property `base_modifications` (List[str])
  # The chemical modifications to bases in a DNA sequence that are detected in this file.

  # uncomment below to test the property
  #expect_equal(model.instance$`base_modifications`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (str)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (List[str])

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("summary", {
  # tests for the property `summary` (str)
  # A summary of the sequence file.

  # uncomment below to test the property
  #expect_equal(model.instance$`summary`, "EXPECTED_RESULT")
})

test_that("integrated_in", {
  # tests for the property `integrated_in` (List[str])
  # Construct library set(s) that this file was used for in insert design.

  # uncomment below to test the property
  #expect_equal(model.instance$`integrated_in`, "EXPECTED_RESULT")
})

test_that("input_file_for", {
  # tests for the property `input_file_for` (List[str])
  # The files which are derived from this file.

  # uncomment below to test the property
  #expect_equal(model.instance$`input_file_for`, "EXPECTED_RESULT")
})

test_that("gene_list_for", {
  # tests for the property `gene_list_for` (List[str])
  # File Set(s) that this file is a gene list for.

  # uncomment below to test the property
  #expect_equal(model.instance$`gene_list_for`, "EXPECTED_RESULT")
})

test_that("loci_list_for", {
  # tests for the property `loci_list_for` (List[str])
  # File Set(s) that this file is a loci list for.

  # uncomment below to test the property
  #expect_equal(model.instance$`loci_list_for`, "EXPECTED_RESULT")
})

test_that("href", {
  # tests for the property `href` (str)
  # The download path to obtain file.

  # uncomment below to test the property
  #expect_equal(model.instance$`href`, "EXPECTED_RESULT")
})

test_that("s3_uri", {
  # tests for the property `s3_uri` (str)
  # The S3 URI of public file object.

  # uncomment below to test the property
  #expect_equal(model.instance$`s3_uri`, "EXPECTED_RESULT")
})

test_that("upload_credentials", {
  # tests for the property `upload_credentials` (object)
  # The upload credentials for S3 to submit the file content.

  # uncomment below to test the property
  #expect_equal(model.instance$`upload_credentials`, "EXPECTED_RESULT")
})

test_that("seqspecs", {
  # tests for the property `seqspecs` (List[str])
  # Link(s) to the associated seqspec YAML configuration file(s).

  # uncomment below to test the property
  #expect_equal(model.instance$`seqspecs`, "EXPECTED_RESULT")
})
