# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Publication")

model_instance <- Publication$new()

test_that("release_timestamp", {
  # tests for the property `release_timestamp` (str)
  # The date the object was released.

  # uncomment below to test the property
  #expect_equal(model.instance$`release_timestamp`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (str)
  # The status of the metadata object.

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("lab", {
  # tests for the property `lab` (str)
  # Lab associated with the submission.

  # uncomment below to test the property
  #expect_equal(model.instance$`lab`, "EXPECTED_RESULT")
})

test_that("award", {
  # tests for the property `award` (str)
  # Grant associated with the submission.

  # uncomment below to test the property
  #expect_equal(model.instance$`award`, "EXPECTED_RESULT")
})

test_that("attachment", {
  # tests for the property `attachment` (Attachment)

  # uncomment below to test the property
  #expect_equal(model.instance$`attachment`, "EXPECTED_RESULT")
})

test_that("schema_version", {
  # tests for the property `schema_version` (str)
  # The version of the JSON schema that the server uses to validate the object.

  # uncomment below to test the property
  #expect_equal(model.instance$`schema_version`, "EXPECTED_RESULT")
})

test_that("uuid", {
  # tests for the property `uuid` (str)
  # The unique identifier associated with every object.

  # uncomment below to test the property
  #expect_equal(model.instance$`uuid`, "EXPECTED_RESULT")
})

test_that("notes", {
  # tests for the property `notes` (str)
  # DACC internal notes.

  # uncomment below to test the property
  #expect_equal(model.instance$`notes`, "EXPECTED_RESULT")
})

test_that("aliases", {
  # tests for the property `aliases` (List[str])
  # Lab specific identifiers to reference an object.

  # uncomment below to test the property
  #expect_equal(model.instance$`aliases`, "EXPECTED_RESULT")
})

test_that("creation_timestamp", {
  # tests for the property `creation_timestamp` (str)
  # The date the object was created.

  # uncomment below to test the property
  #expect_equal(model.instance$`creation_timestamp`, "EXPECTED_RESULT")
})

test_that("submitted_by", {
  # tests for the property `submitted_by` (str)
  # The user who submitted the object.

  # uncomment below to test the property
  #expect_equal(model.instance$`submitted_by`, "EXPECTED_RESULT")
})

test_that("submitter_comment", {
  # tests for the property `submitter_comment` (str)
  # Additional information specified by the submitter to be displayed as a comment on the portal.

  # uncomment below to test the property
  #expect_equal(model.instance$`submitter_comment`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (str)
  # A plain text description of the object.

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("title", {
  # tests for the property `title` (str)
  # Title of the publication or communication.

  # uncomment below to test the property
  #expect_equal(model.instance$`title`, "EXPECTED_RESULT")
})

test_that("abstract", {
  # tests for the property `abstract` (str)
  # Abstract of the publication or communication.

  # uncomment below to test the property
  #expect_equal(model.instance$`abstract`, "EXPECTED_RESULT")
})

test_that("authors", {
  # tests for the property `authors` (str)
  # The authors of the publication.

  # uncomment below to test the property
  #expect_equal(model.instance$`authors`, "EXPECTED_RESULT")
})

test_that("date_published", {
  # tests for the property `date_published` (str)
  # The date the publication or communication was published; must be in YYYY-MM-DD format.

  # uncomment below to test the property
  #expect_equal(model.instance$`date_published`, "EXPECTED_RESULT")
})

test_that("date_revised", {
  # tests for the property `date_revised` (str)
  # The date the publication was revised.

  # uncomment below to test the property
  #expect_equal(model.instance$`date_revised`, "EXPECTED_RESULT")
})

test_that("issue", {
  # tests for the property `issue` (str)
  # The issue of the publication.

  # uncomment below to test the property
  #expect_equal(model.instance$`issue`, "EXPECTED_RESULT")
})

test_that("page", {
  # tests for the property `page` (str)
  # Pagination of the reference

  # uncomment below to test the property
  #expect_equal(model.instance$`page`, "EXPECTED_RESULT")
})

test_that("volume", {
  # tests for the property `volume` (str)
  # The volume of the publication.

  # uncomment below to test the property
  #expect_equal(model.instance$`volume`, "EXPECTED_RESULT")
})

test_that("journal", {
  # tests for the property `journal` (str)
  # The journal of the publication.

  # uncomment below to test the property
  #expect_equal(model.instance$`journal`, "EXPECTED_RESULT")
})

test_that("publication_identifiers", {
  # tests for the property `publication_identifiers` (List[str])
  # The publication identifiers associated with this publication object.

  # uncomment below to test the property
  #expect_equal(model.instance$`publication_identifiers`, "EXPECTED_RESULT")
})

test_that("published_by", {
  # tests for the property `published_by` (List[str])
  # The affiliation of the lab with a larger organization, such as IGVF.

  # uncomment below to test the property
  #expect_equal(model.instance$`published_by`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (str)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (List[str])

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("summary", {
  # tests for the property `summary` (str)
  # A summary of the publication.

  # uncomment below to test the property
  #expect_equal(model.instance$`summary`, "EXPECTED_RESULT")
})

test_that("publication_year", {
  # tests for the property `publication_year` (int)
  # The year the publication was published.

  # uncomment below to test the property
  #expect_equal(model.instance$`publication_year`, "EXPECTED_RESULT")
})

test_that("samples", {
  # tests for the property `samples` (List[str])
  # The samples associated with this publication.

  # uncomment below to test the property
  #expect_equal(model.instance$`samples`, "EXPECTED_RESULT")
})

test_that("donors", {
  # tests for the property `donors` (List[str])
  # The donors associated with this publication.

  # uncomment below to test the property
  #expect_equal(model.instance$`donors`, "EXPECTED_RESULT")
})

test_that("file_sets", {
  # tests for the property `file_sets` (List[str])
  # The file sets associated with this publication.

  # uncomment below to test the property
  #expect_equal(model.instance$`file_sets`, "EXPECTED_RESULT")
})

test_that("workflows", {
  # tests for the property `workflows` (List[str])
  # The workflows associated with this publication.

  # uncomment below to test the property
  #expect_equal(model.instance$`workflows`, "EXPECTED_RESULT")
})

test_that("software", {
  # tests for the property `software` (List[str])
  # The software associated with this publication.

  # uncomment below to test the property
  #expect_equal(model.instance$`software`, "EXPECTED_RESULT")
})

test_that("software_versions", {
  # tests for the property `software_versions` (List[str])
  # The software versions associated with this publication.

  # uncomment below to test the property
  #expect_equal(model.instance$`software_versions`, "EXPECTED_RESULT")
})
