# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SearchFacet")

model_instance <- SearchFacet$new()

test_that("var_field", {
  # tests for the property `var_field` (str)

  # uncomment below to test the property
  #expect_equal(model.instance$`var_field`, "EXPECTED_RESULT")
})

test_that("title", {
  # tests for the property `title` (str)

  # uncomment below to test the property
  #expect_equal(model.instance$`title`, "EXPECTED_RESULT")
})

test_that("terms", {
  # tests for the property `terms` (List[object])

  # uncomment below to test the property
  #expect_equal(model.instance$`terms`, "EXPECTED_RESULT")
})
