name: R API Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Build and check package
        run: |
          R CMD build .
          R CMD check *tar.gz --no-manual

      - name: Install package
        run: R CMD INSTALL --preclean *tar.gz

      - name: Run tests
        run: |
          library(igvfclient)
          source("tests/test_endpoints.R")
        shell: Rscript {0}
